services:
  vprodb:
    build:
      context: ./Docker-files/db
      dockerfile: Dockerfile
    image: vproconatiners/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
      build:
        context: ./Docker-files/app
        dockerfile: Dockerfile
      image: vproconatiners/vprofileapp
      container_name: vproapp
      ports:
      - "8080:8080"
      volumes:
      - vproappdata:/usr/local/tomcat/webapps
  
  vproweb:
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    image: vproconatiners/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
    
volumes:
  vprodbdata: {}
  vproappdata: {}